### PR TITLE
chore: npm scripts for examples

### PR DESCRIPTION
**Pull request by zhuangya**

### CODE REVIEW

**Comment by zhuangya** [comment]
since @ssreekanth pointed out the example problem.
i just checked it out by myself.

and i'm kind of confusing about the examples' `package.json`

so here is the fix. ;)

**Comment by ssreekanth** [comment]
You really don't need this. use 'gulp serve' command to start the examples' app.

**Comment by zhuangya** [comment]
@ssreekanth updated to `"start": "gulp serve"`

**Comment by ssreekanth** [comment]
@zhuangya @Quramy Looks good to me.

**Comment by ssreekanth** [comment]
@zhuangya @Quramy Looks good to me!

**Comment by Quramy** [comment]
@zhuangya Thx!

**Pull request merged**
